- hosts: master1
  become: true
  tasks:
    - name: Get kubeconfig_file
      shell: "cat $HOME/.kube/config"
      register: kubeconfig_file

- hosts: localhost
  vars:
    kubeconfig: "{{ hostvars['master1']['kubeconfig_file']['stdout'] }}"
  tasks:
    - name: Write kubeconfig
      lineinfile:
        path: ./kubeconfig
        line: "{{ kubeconfig }}"
        create: yes
        mode: 0644
