- hosts: localhost
  tasks:
    - name: Get control_plane and calico from localhost
      shell: "cat ./control_plane.sh"
      register: control_plane

- hosts: firstmaster
  become: true
  vars:
    control_plane_content: "{{ hostvars['localhost']['control_plane']['stdout'] }}"
  tasks:
    - name: Write control_plane and calico
      lineinfile:
        path: $HOME/control_plane.sh
        line: "{{ control_plane_content }}"
        create: yes
        mode: 0755
    - name: Run control_plane and calico
      command: sh $HOME/control_plane.sh
