- hosts: localhost
  tasks:
    - name: Get control_plane and calico from localhost
      shell: "cat ./control_plane.sh"
      register: control_plane

- hosts: firstmaster
  become: true
  tasks:
  - name: Print join master token
    shell: kubeadm token create --print-join-command
    register: master_token
  - name: Log token
    debug: 
      msg: "{{ master_token.stdout_lines }}"
- hosts: othermasters
  become: true
  vars:
    master_token: "{{ hostvars['firstmaster']['master_token']['stdout'] }}"
    control_plane_content: "{{ hostvars['localhost']['control_plane']['stdout'] }}"
  tasks:
  - name: Join masters
    command: "{{ master_token }}"
    register: output

  - name: Log result
    debug: 
      msg: "{{ output.stdout_lines }}"

  tasks:
    - name: Run control_plane and calico
      command: "{{ control_plane_content }}"
